version: "3"
services:
  app-deploy:
    build:
      context: .
      dockerfile: Dockerfile-deployment
    volumes:
      - ./:/usr/src/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
